blank_issues_enabled: false
contact_links:
  - name: ConvertKit support
    url: https://convertkit.com/support/
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the ConvertKit PHP SDK.

      If you're having general trouble with your ConvertKit integration, please reach out to support.